import fs from 'node:fs';
import path from 'node:path';

const out='dist';
fs.rmSync(out,{recursive:true,force:true}); fs.mkdirSync(out,{recursive:true});
const origin='https://marginflips-tools.peachy-lark-8663.chatgpt.site';
const buy='https://payhip.com/b/pTi34';
const brand='MarginFlips';

const tools=[
 ['profit','Reseller Profit Calculator','See the estimated profit, margin, ROI, fees, and total cost of a sale.'],
 ['roi','ROI Calculator','Measure the return on the money invested in an item.'],
 ['break-even','Break-Even Price Calculator','Estimate the minimum sale price needed to avoid a loss.'],
 ['max-buy','Maximum Buy Price Calculator','Find a purchase-price ceiling based on your target profit or ROI.'],
 ['marketplace-fee','Marketplace Fee & Profit Calculator','Test editable marketplace fee assumptions without relying on outdated rates.'],
 ['offer','Offer Calculator','Evaluate the economics of accepting a buyer offer.']
];

const guides=[
 {slug:'calculate-reselling-profit',title:'How to Calculate Reselling Profit',desc:'A clear way to account for fees, shipping, item cost, and overlooked expenses.',body:`<p>Reselling profit is what remains after every cost tied to a sale is subtracted from the revenue you receive. The useful formula is:</p><div class="formula">Net profit = selling price − percentage fees − fixed fees − item cost − shipping − all other costs</div><h2>A complete example</h2><p>Suppose an item sells for $80. You paid $24, the marketplace fee is 13%, the fixed fee is $0.30, shipping costs $8.50, packaging costs $1.20, and promoted-listing cost is $2.</p><ul><li>Percentage fee: $80 × 13% = $10.40</li><li>Total costs: $24 + $10.40 + $0.30 + $8.50 + $1.20 + $2 = $46.40</li><li>Estimated net profit: $80 − $46.40 = $33.60</li></ul><p>Use the <a href="/tools/profit/">profit calculator</a> to run the same calculation with your own numbers.</p><h2>Profit is not the same as cash received</h2><p>A marketplace payout may already have some fees deducted, but that payout still does not account for what you paid for the item, packing materials, repairs, mileage, or other business expenses. Record each cost once and avoid mixing personal overhead with item-level expenses unless you have a consistent allocation method.</p><h2>Before listing</h2><p>Calculate at the price you realistically expect to accept, not only at an optimistic list price. Then test a lower offer so you know your floor before a buyer negotiates.</p>`},
 {slug:'profit-margin-vs-roi',title:'Profit Margin vs. ROI for Resellers',desc:'Understand what each percentage measures and when each one helps.',body:`<p>Profit margin and ROI answer different questions. Margin measures profit relative to revenue. ROI measures profit relative to the money invested.</p><div class="formula">Profit margin = net profit ÷ selling price × 100<br>ROI = net profit ÷ total investment × 100</div><h2>One sale, two useful percentages</h2><p>If an item sells for $75, produces $25 in net profit, and required $30 of total investment, its margin is 33.33% while its ROI is 83.33%.</p><p>Margin helps you understand how much room a sale has for discounts, returns, and unexpected costs. ROI helps compare sourcing opportunities that require different amounts of cash.</p><h2>Use both, not either</h2><p>A high ROI on a very cheap item may still produce too few dollars for the time involved. A healthy dollar profit with a weak ROI may tie up too much capital. Compare net profit, margin, ROI, time, and expected sell-through together. Check a scenario with the <a href="/tools/roi/">ROI calculator</a>.</p>`},
 {slug:'how-much-to-pay',title:'How Much Should You Pay for an Item to Resell?',desc:'Work backward from the expected sale price and your required return.',body:`<p>The safest sourcing decision starts with a conservative expected selling price and works backward. Subtract selling fees, shipping, preparation costs, and your desired profit. What remains is the most you can pay.</p><div class="formula">Maximum buy price = expected sale price − selling costs − desired profit</div><p>When the goal is ROI instead of a fixed dollar profit, the maximum buy price must also satisfy the return you require. Our <a href="/tools/max-buy/">maximum buy price calculator</a> handles both approaches.</p><h2>Use realistic sale prices</h2><p>Look at comparable completed sales where available, then account for condition, season, competition, and how quickly you need to sell. Asking prices do not prove demand.</p><h2>Leave a buffer</h2><p>Unknown defects, returns, extra packing, and price negotiation can erase a thin margin. A sourcing ceiling is a decision boundary, not a prediction or guarantee.</p>`},
 {slug:'break-even-selling-price',title:'How to Calculate Your Break-Even Selling Price',desc:'Find the price where revenue approximately equals all selling costs.',body:`<p>A break-even price is the sale price at which estimated profit reaches zero. When fees are a percentage of the selling price, you cannot simply add that percentage to your costs.</p><div class="formula">Break-even price = fixed costs ÷ (1 − percentage fee rate)</div><p>If fixed costs total $34 and percentage fees are 15%, break-even is $34 ÷ 0.85 = $40. A fee assumption of 100% or more makes a finite break-even price impossible.</p><p>Use the <a href="/tools/break-even/">break-even calculator</a> to combine item cost, shipping, fixed fees, and other costs correctly.</p><h2>What break-even does not include</h2><p>Unless you enter them, the result will not include returns, income taxes, your labor, inventory storage, or general overhead. Treat it as a planning estimate and verify the fee rules that apply to your transaction.</p>`},
 {slug:'evaluate-buyer-offer',title:'How to Evaluate a Buyer Offer',desc:'Turn an offer notification into a calm, repeatable decision.',body:`<p>An offer is worth evaluating against the economics of the offered price—not the original list price. Recalculate percentage fees, then subtract item cost, shipping, preparation, and other expenses.</p><h2>Set the floor before negotiating</h2><p>Choose either a minimum dollar profit or a minimum ROI. If an offer misses that target, calculate the counteroffer needed to reach it instead of responding from memory.</p><p>The <a href="/tools/offer/">offer calculator</a> labels the estimate as meeting or missing your selected threshold and shows the gap. That language supports a decision; it does not promise the sale will be profitable.</p><h2>Consider non-financial factors</h2><p>Time in inventory, storage pressure, return risk, and confidence in your cost estimate may justify a different choice. Keep the calculation visible so the tradeoff is deliberate.</p>`},
 {slug:'costs-beginners-forget',title:'Common Reselling Costs Beginners Forget',desc:'A practical checklist for expenses that quietly reduce profit.',body:`<p>Small costs become material when repeated across many orders. Commonly missed item-level expenses include packaging, seller-paid postage, promoted listings, cleaning supplies, repair parts, authentication, and fixed transaction charges.</p><h2>Separate direct and shared costs</h2><p>Direct costs belong to one item. Shared costs—software, storage, equipment, and mileage—support the broader business. Track both, but avoid counting the same expense twice.</p><ul><li>Purchase price and inbound shipping</li><li>Selling and payment fees</li><li>Outbound shipping and insurance</li><li>Boxes, mailers, tape, labels, and void fill</li><li>Cleaning, testing, repair, or replacement parts</li><li>Advertising and promotion</li><li>Returns, refunds, and damaged shipments</li></ul><p>Start with the <a href="/tools/profit/">profit calculator</a>, then save a consistent cost checklist for every listing.</p>`},
 {slug:'marketplace-fees',title:'How Marketplace Fees Affect Reseller Profit',desc:'Model percentage and fixed fees without assuming rates stay unchanged.',body:`<p>Marketplace fees can include a percentage of the transaction, a fixed charge, optional promotion, payment processing, category-specific rates, or other adjustments. The fee base may also differ by marketplace.</p><h2>Use editable assumptions</h2><p>A preset can become outdated. Enter and verify the fee rate that applies to your category, account, location, and transaction. MarginFlips does not automatically update marketplace fees.</p><p>A $100 sale with a 12% fee and a $0.30 fixed fee creates an estimated $12.30 in fees before shipping and item cost. At 16%, the same sale creates $16.30 in fees—a $4 difference in profit.</p><p>Compare assumptions with the <a href="/tools/marketplace-fee/">marketplace fee and profit calculator</a>.</p>`},
 {slug:'sourcing-checklist',title:'A Practical Reseller Sourcing Checklist',desc:'A repeatable pre-purchase screen for price, condition, demand, and risk.',body:`<p>A good sourcing check is short enough to use in the field and strict enough to prevent hopeful purchases.</p><ol><li>Identify the exact item, model, size, and condition.</li><li>Check credible sold-price evidence where available.</li><li>Estimate a conservative selling price.</li><li>Confirm category restrictions and shipping practicality.</li><li>Enter every expected cost.</li><li>Calculate net profit, margin, ROI, and maximum buy price.</li><li>Allow a buffer for negotiation and surprises.</li><li>Pass when the numbers depend on a best-case outcome.</li></ol><p>Use the <a href="/tools/max-buy/">maximum buy price calculator</a> before purchasing, then record the assumptions you used so you can compare estimates with actual results later.</p>`}
];

const icon=`<svg aria-hidden="true" viewBox="0 0 40 40"><rect x="3" y="3" width="34" height="34" rx="10" fill="#132c2a"/><path d="M11 27V14h18M12 24l6-6 4 4 7-8" fill="none" stroke="#f3c969" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/></svg>`;
const nav=`<header><a class="brand" href="/">${icon}<span>${brand}</span></a><button class="menu" aria-label="Toggle menu" aria-expanded="false">Menu</button><nav aria-label="Main navigation"><a href="/tools/">Tools</a><a href="/guides/">Guides</a><a href="/product/">Excel Toolkit</a><a href="/resources/">Resources</a><a href="/about/">About</a></nav></header>`;
const footer=`<footer><div><a class="brand foot" href="/">${icon}<span>${brand}</span></a><p>Practical calculations for smarter reselling decisions.</p></div><div><h2>Explore</h2><a href="/tools/">Free tools</a><a href="/guides/">Guides</a><a href="/resources/">Resources</a></div><div><h2>Information</h2><a href="/about/">About</a><a href="/contact/">Contact</a><a href="/privacy/">Privacy</a><a href="/terms/">Terms</a><a href="/disclaimer/">Disclaimer</a></div><p class="legal">© 2026 MarginFlips. Estimates only. Marketplace names belong to their respective owners. MarginFlips is not affiliated with them.</p></footer>`;

function layout({title,desc,path='/',body,type='website'}){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} | ${brand}</title><meta name="description" content="${desc}"><link rel="canonical" href="${origin}${path}"><meta property="og:type" content="${type}"><meta property="og:title" content="${title} | ${brand}"><meta property="og:description" content="${desc}"><meta property="og:url" content="${origin}${path}"><meta name="theme-color" content="#132c2a"><link rel="stylesheet" href="/assets/style.css"><script defer src="/assets/app.js"></script><script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':type==='article'?'Article':'WebPage',name:title,description:desc,url:origin+path,publisher:{'@type':'Organization',name:brand}})}</script></head><body>${nav}<main>${body}</main>${footer}</body></html>`}
function write(route,html){const dir=path.join(out,route);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'index.html'),html)}
function cards(items,base){return `<div class="card-grid">${items.map(([s,t,d])=>`<a class="card" href="/${base}/${s}/"><span class="eyebrow">Free tool</span><h3>${t}</h3><p>${d}</p><span class="link">Open calculator →</span></a>`).join('')}</div>`}

const home=`<section class="hero"><div><span class="eyebrow">Free reseller decision tools</span><h1>Know the numbers before you buy—or accept an offer.</h1><p>Calculate estimated profit, ROI, break-even price, and sourcing limits with clear formulas and editable assumptions.</p><div class="actions"><a class="button" href="/tools/profit/" data-event="hero_profit">Try the Profit Calculator</a><a class="button secondary" href="/tools/">Explore Free Tools</a></div></div><div class="mini-calc"><span class="eyebrow">Quick example</span><div class="mini-row"><span>Sale price</span><b>$80.00</b></div><div class="mini-row"><span>Total costs</span><b>$46.40</b></div><div class="mini-result"><span>Estimated profit</span><strong>$33.60</strong></div><small>Example only. Verify your own fees and costs.</small></div></section><section><span class="eyebrow">Popular calculators</span><h2>Make each listing decision with a complete cost picture.</h2>${cards(tools,'tools')}</section><section class="split"><div><span class="eyebrow">The method</span><h2>Revenue is only the starting point.</h2><p>Every calculator separates sale revenue, percentage fees, fixed charges, item cost, shipping, and other expenses. You can see the formula, change assumptions, and understand unusual results.</p><a class="text-link" href="/guides/calculate-reselling-profit/">Learn how profit is calculated →</a></div><div class="stack"><div><b>1</b><span><strong>Enter the deal</strong><small>Use the price and costs you genuinely expect.</small></span></div><div><b>2</b><span><strong>Check the return</strong><small>Review dollars, margin, and ROI together.</small></span></div><div><b>3</b><span><strong>Stress-test it</strong><small>Try a lower offer or higher cost before deciding.</small></span></div></div></section><section><span class="eyebrow">Practical guides</span><h2>Understand the calculation, not just the output.</h2><div class="article-grid">${guides.slice(0,4).map(g=>`<a class="article-card" href="/guides/${g.slug}/"><h3>${g.title}</h3><p>${g.desc}</p><span>Read guide →</span></a>`).join('')}</div></section>${productCta()}`;
write('',layout({title:'Free Reseller Calculators & Profit Tools',desc:'Free calculators and practical guides for reseller profit, ROI, break-even pricing, sourcing, marketplace fees, and buyer offers.',body:home}));

function calculatorBody(kind,title,desc){const fields={profit:[['sale','Selling price',80],['cost','Item / purchase cost',24],['feePct','Marketplace fee %',13],['fixed','Payment / fixed fee',0.3],['shipping','Seller-paid shipping',8.5],['pack','Packaging cost',1.2],['ad','Advertising cost',2],['prep','Repair / preparation cost',0],['other','Other costs',0]],roi:[['investment','Total investment / cost',30],['profit','Net profit',25]],'break-even':[['cost','Item / purchase cost',24],['feePct','Percentage fee %',15],['fixed','Fixed fee',0.3],['shipping','Seller-paid shipping',8.5],['other','Other costs',1.2]],'max-buy':[['sale','Expected selling price',80],['feePct','Percentage fee %',13],['fixed','Fixed fee',0.3],['shipping','Shipping and other non-item costs',9.7],['targetProfit','Desired profit',25],['targetRoi','Desired ROI % (optional)',0]],'marketplace-fee':[['sale','Selling price',80],['cost','Item / purchase cost',24],['feePct','Your fee assumption %',13],['fixed','Your fixed fee assumption',0.3],['shipping','Seller-paid shipping',8.5],['other','Other costs',1.2]],offer:[['list','Original / list price',90],['offer','Buyer offer',72],['cost','Item / purchase cost',24],['feePct','Percentage fee %',13],['fixed','Fixed fee',0.3],['shipping','Seller-paid shipping',8.5],['other','Other costs',1.2],['minProfit','Minimum desired profit',20],['minRoi','Minimum desired ROI %',0]]}[kind];return `<section class="tool-head"><span class="eyebrow">Free calculator</span><h1>${title}</h1><p>${desc}</p></section><section class="calculator" data-calculator="${kind}" data-event="calculator_view"><form novalidate><div class="fields">${fields.map(([id,label,val])=>`<label>${label}<span class="input-wrap"><span>${id.toLowerCase().includes('pct')||id.toLowerCase().includes('roi')?'%':'$'}</span><input inputmode="decimal" name="${id}" value="${val}" aria-describedby="${id}-error"></span><small class="field-error" id="${id}-error"></small></label>`).join('')}</div><button class="button" type="submit">Calculate</button><button class="reset" type="button">Reset example</button></form><aside class="results" aria-live="polite"><span class="eyebrow">Estimated result</span><div class="result-content"><p>Enter your assumptions, then calculate.</p></div></aside></section><section class="explain"><h2>How this calculation works</h2><div class="formula" data-formula="${kind}"></div><p>Blank fields are treated as zero only when zero is meaningful. Values must be non-negative. Percentage-based selling fees must stay below 100% for reverse-price calculations. Results are estimates and can differ from actual payouts.</p></section>${productCta()}`}
for(const [slug,title,desc] of tools)write(`tools/${slug}`,layout({title,desc,path:`/tools/${slug}/`,body:calculatorBody(slug,title,desc)}));
write('tools',layout({title:'Free Reseller Calculators',desc:'Six free calculators for reseller profit, ROI, break-even pricing, maximum buy price, fees, and buyer offers.',path:'/tools/',body:`<section class="page-head"><span class="eyebrow">Free tools</span><h1>Run the numbers before the deal.</h1><p>Each calculator uses your assumptions. No account, fee lookup, or purchase is required.</p></section>${cards(tools,'tools')}<section class="notice"><h2>Use current fee information</h2><p>Marketplace rules and fees change. These tools do not automatically update rates. Verify the fees for your category, location, and transaction before making a decision.</p></section>`}));
write('guides',layout({title:'Reseller Guides',desc:'Practical guides to reseller profit, ROI, break-even pricing, buyer offers, marketplace fees, and sourcing.',path:'/guides/',body:`<section class="page-head"><span class="eyebrow">Reseller guides</span><h1>Build a repeatable decision process.</h1><p>Clear explanations and examples for the numbers behind sourcing, pricing, and offers.</p></section><div class="article-grid all">${guides.map(g=>`<a class="article-card" href="/guides/${g.slug}/" data-event="guide_visit"><h2>${g.title}</h2><p>${g.desc}</p><span>Read guide →</span></a>`).join('')}</div>`}));
for(const g of guides)write(`guides/${g.slug}`,layout({title:g.title,desc:g.desc,path:`/guides/${g.slug}/`,type:'article',body:`<article><a class="back" href="/guides/">← All guides</a><span class="eyebrow">Practical guide</span><h1>${g.title}</h1><p class="lede">${g.desc}</p>${g.body}<div class="article-note"><strong>Keep the estimate honest.</strong><p>Fee structures and actual costs can change. Verify the rules that apply to your sale and treat every result as planning information.</p></div></article>${productCta()}`}));

function productCta(){return `<section class="product-cta"><div><span class="eyebrow">Need everything in one workbook?</span><h2>Move from one-off calculations to a complete resale workflow.</h2><p>The Reseller Profit Tool includes an Offer Analyzer, Platform Comparison, Sourcing Log, Sales Log, Dashboard, Target Pricing, Maximum Purchase Price, and Break-Even Analysis.</p></div><a class="button gold" href="${buy}" target="_blank" rel="noopener" data-event="payhip_click">Get the Full Reseller Profit Tool — $9.99</a></section>`}
write('product',layout({title:'Reseller Profit Tool for Excel',desc:'A $9.99 Excel decision-support toolkit for reseller pricing, offers, sourcing, sales tracking, and profit analysis.',path:'/product/',body:`<section class="product-hero"><div><span class="eyebrow">Excel toolkit · $9.99</span><h1>Your reseller calculations, sourcing, offers, and sales—in one workbook.</h1><p>Reseller Profit Tool is a practical Microsoft Excel toolkit for evaluating deals and recording actual results without macros or external plugins.</p><a class="button gold" href="${buy}" target="_blank" rel="noopener" data-event="payhip_click">Get the Reseller Profit Tool — $9.99</a><small>Digital Excel (.xlsx) product delivered through Payhip.</small></div><div class="feature-panel"><h2>Included workflows</h2><ul><li>Net profit, margin, and ROI</li><li>Break-even and target pricing</li><li>Maximum purchase price</li><li>ACCEPT / COUNTER / DECLINE offer analysis</li><li>Multi-platform estimate comparison</li><li>Sourcing and sales logs</li><li>Performance dashboard</li></ul></div></section><section class="split"><div><h2>What the free tools do</h2><p>Each website calculator solves one decision quickly, with no download required.</p></div><div><h2>Why use the workbook</h2><p>Keep related calculations and records together, compare platforms, analyze offers, and review sales from a single reusable file.</p></div></section><section class="notice"><h2>Important</h2><p>The workbook provides estimates based on your inputs. Marketplace fees are not guaranteed to be current or perfectly accurate. Verify applicable fees. No profit is guaranteed.</p></section>`}));
write('resources',layout({title:'Reseller Resources',desc:'A transparent home for future reseller supply and software recommendations.',path:'/resources/',body:`<section class="page-head"><span class="eyebrow">Resources</span><h1>Useful reseller resources—without invented endorsements.</h1><p>This section is prepared for carefully reviewed recommendations on shipping supplies, scales, label printers, photo equipment, storage, and reseller software.</p></section><section class="empty-state"><h2>No sponsored recommendations yet.</h2><p>MarginFlips does not currently list affiliate partners here. If affiliate links are added later, they will be clearly identified and accompanied by a disclosure.</p><a class="button secondary" href="/tools/">Use the free tools</a></section>`}));
const simple={about:['About MarginFlips','MarginFlips is an independent educational and calculation website for individual resellers and flippers. Its purpose is to make cost, fee, profit, ROI, pricing, sourcing, and offer decisions easier to understand.','The calculators provide standalone value and use assumptions entered by the visitor. MarginFlips does not claim personal marketplace selling experience, guaranteed outcomes, or affiliation with any marketplace.'],contact:['Contact','Questions about the Reseller Profit Tool can be directed to the seller through the secure product page.','<a class="button secondary" href="https://payhip.com/b/pTi34" target="_blank" rel="noopener">Open the Payhip product page</a><p>For an order-specific question, include the purchase email or receipt details in your message to the seller. Do not post payment information publicly.</p>'],privacy:['Privacy Policy','This V1 website does not require an account and does not intentionally collect the numbers entered into calculators. Calculations run in the visitor’s browser.','The site may be updated to use privacy-conscious analytics, advertising, consent tools, or affiliate links. If that happens, this policy should be updated before those services are enabled. Hosting providers may process standard technical information such as IP addresses, device data, and request logs for security and delivery. External links, including Payhip, are governed by their own privacy policies.'],terms:['Terms of Use','By using MarginFlips, you agree to use its calculators and content for general informational and planning purposes only.','Results depend on the inputs provided and may differ from actual marketplace charges, payouts, taxes, returns, or business results. You remain responsible for verifying applicable fees, policies, restrictions, and costs. The site is provided without warranties of accuracy, availability, or fitness for a particular purpose to the extent permitted by law.'],disclaimer:['Disclaimer','All calculations and content on MarginFlips are estimates provided for educational and decision-support purposes.','Marketplace fee structures, policies, taxes, and transaction details can change. Verify the information applicable to your account, category, location, and sale. MarginFlips does not guarantee profits and does not provide accounting, tax, legal, investment, or financial advice. Marketplace names and trademarks belong to their respective owners. MarginFlips is not affiliated with eBay, Poshmark, Mercari, Depop, Whatnot, Etsy, Facebook Marketplace, or other marketplaces unless explicitly stated.']};
for(const [slug,[title,intro,body]] of Object.entries(simple))write(slug,layout({title,desc:intro,path:`/${slug}/`,body:`<section class="legal-page"><span class="eyebrow">Information</span><h1>${title}</h1><p class="lede">${intro}</p><p>${body}</p><p class="updated">Last updated: September 7, 2026</p></section>`}));
write('404',layout({title:'Page Not Found',desc:'The requested MarginFlips page could not be found.',path:'/404/',body:`<section class="empty-state"><span class="eyebrow">404</span><h1>That page is not here.</h1><p>Try a free calculator or browse the reseller guides.</p><div class="actions"><a class="button" href="/tools/">Open tools</a><a class="button secondary" href="/guides/">Browse guides</a></div></section>`}));
fs.mkdirSync(path.join(out,'assets'),{recursive:true});
fs.copyFileSync('src/style.css',path.join(out,'assets/style.css')); fs.copyFileSync('src/app.js',path.join(out,'assets/app.js'));
fs.writeFileSync(path.join(out,'robots.txt'),`User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`);
const urls=['/','/tools/','/guides/','/product/','/resources/','/about/','/contact/','/privacy/','/terms/','/disclaimer/',...tools.map(x=>`/tools/${x[0]}/`),...guides.map(x=>`/guides/${x.slug}/`)];
fs.writeFileSync(path.join(out,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(u=>`<url><loc>${origin}${u}</loc></url>`).join('')}</urlset>`);
fs.writeFileSync(path.join(out,'_redirects'),`/404.html /404/index.html 404\n`);
console.log(`Built ${urls.length} crawlable pages plus 404.`);
