const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(Number.isFinite(n)?n:0);const pct=n=>`${(Number.isFinite(n)?n:0).toFixed(2)}%`;const qs=(s,e=document)=>e.querySelector(s);document.querySelector('.menu')?.addEventListener('click',e=>{const n=qs('header nav');n.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',n.classList.contains('open'))});
const formulas={profit:'Net profit = selling price − percentage fee − fixed fee − item cost − shipping − packaging − advertising − preparation − other costs',roi:'ROI = net profit ÷ total investment × 100','break-even':'Break-even price = fixed costs ÷ (1 − percentage fee rate)','max-buy':'Maximum buy price = expected selling price − selling fees − non-item costs − desired profit (and may also be limited by desired ROI)','marketplace-fee':'Estimated fee = selling price × your fee assumption + your fixed fee',offer:'Offer profit = buyer offer − percentage fee − fixed fee − item cost − shipping − other costs'};document.querySelectorAll('[data-formula]').forEach(e=>e.textContent=formulas[e.dataset.formula]);
document.addEventListener('click',e=>{const a=e.target.closest('[data-event]');if(a)window.dataLayer?.push({event:a.dataset.event,path:location.pathname})});
function isValidInput(kind,name,n){return Number.isFinite(n)&&((kind==='roi'&&name==='profit')||n>=0)}function calculateROI(investment,profit){return investment>0?profit/investment*100:null}function values(form){const v={},errors=[],kind=form.closest('[data-calculator]')?.dataset.calculator;for(const input of form.elements){if(!input.name)continue;const raw=input.value.trim(),n=raw===''?0:Number(raw),err=qs(`#${input.name}-error`);err.textContent='';if(!isValidInput(kind,input.name,n)){err.textContent=kind==='roi'&&input.name==='profit'?'Enter a valid number.':'Enter zero or a positive number.';errors.push(input);continue}v[input.name]=n}return {v,errors}}
function rows(items,note,cls=''){return items.map(([k,v,p])=>`<div class="metric ${p?'primary':''}"><span>${k}</span><strong>${v}</strong></div>`).join('')+`<p class="result-note ${cls}">${note}</p>`}
function calc(kind,v){let fees,total,profit,margin,roi;if(kind==='profit'||kind==='marketplace-fee'){fees=v.sale*v.feePct/100+v.fixed;total=(v.cost||0)+fees+(v.shipping||0)+(v.pack||0)+(v.ad||0)+(v.prep||0)+(v.other||0);profit=v.sale-total;margin=v.sale>0?profit/v.sale*100:0;roi=v.cost>0?profit/v.cost*100:null;return rows([['Estimated total fees',money(fees)],['Estimated total costs',money(total)],['Estimated net profit',money(profit),1],['Profit margin',pct(margin)],['ROI',roi===null?'Not available (zero item cost)':pct(roi)]],profit>=0?'The entered scenario is estimated to be profitable.':'The entered scenario is estimated to produce a loss.',profit>=0?'good':'bad')}
if(kind==='roi'){profit=v.profit;roi=calculateROI(v.investment,profit);return rows([['Profit',money(profit)],['ROI',roi===null?'Not available':pct(roi),1]],v.investment===0?'ROI cannot be calculated when total investment is zero.':roi>=100?'The estimated profit is at least equal to the investment.':roi>=0?'The estimate shows a positive return.':'The estimate shows a negative return.',v.investment===0?'warn':roi>=0?'good':'bad')}
if(kind==='break-even'){if(v.feePct>=100)return rows([['Break-even price','Not possible',1]],'Percentage fees must be below 100% for a finite break-even price.','bad');const fixed=v.cost+v.fixed+v.shipping+v.other,be=fixed/(1-v.feePct/100);return rows([['Fixed costs',money(fixed)],['Break-even selling price',money(be),1]],'At this approximate selling price, estimated revenue equals the entered costs.','good')}
if(kind==='max-buy'){if(v.feePct>=100)return rows([['Maximum buy price','Not possible',1]],'Percentage fees must be below 100%.','bad');const netBeforeBuy=v.sale-(v.sale*v.feePct/100)-v.fixed-v.shipping;let byProfit=netBeforeBuy-v.targetProfit,byRoi=v.targetRoi>0?(netBeforeBuy/(1+v.targetRoi/100)):Infinity,max=Math.min(byProfit,byRoi);return rows([['Available after selling costs',money(netBeforeBuy)],['Limit from profit target',money(byProfit)],['Limit from ROI target',Number.isFinite(byRoi)?money(byRoi):'Not applied'],['Maximum recommended purchase price',money(Math.max(0,max)),1]],max<0?'The desired target is not achievable under these assumptions.':'Paying less than this estimate creates more room for error. Estimate only.',max<0?'bad':'good')}
if(kind==='offer'){fees=v.offer*v.feePct/100+v.fixed;total=v.cost+fees+v.shipping+v.other;profit=v.offer-total;roi=v.cost>0?profit/v.cost*100:null;const meetsProfit=profit>=v.minProfit,meetsRoi=v.minRoi<=0||(roi!==null&&roi>=v.minRoi),ok=meetsProfit&&meetsRoi;let note=ok?'The offer meets the entered minimum target(s).':'The offer misses at least one entered minimum target.';return rows([['Buyer offer',money(v.offer)],['Estimated fees',money(fees)],['Estimated net profit',money(profit),1],['Estimated ROI',roi===null?'Not available':pct(roi)],['Decision support',ok?'MEETS TARGET':'BELOW TARGET']],note,ok?'good':'warn')}}
document.querySelectorAll('[data-calculator]').forEach(box=>{const form=qs('form',box),initial=new FormData(form),kind=box.dataset.calculator;form.addEventListener('submit',e=>{e.preventDefault();const {v,errors}=values(form);if(errors.length){errors[0].focus();qs('.result-content',box).innerHTML='<p class="result-note bad">Correct the highlighted input before calculating.</p>';return}qs('.result-content',box).innerHTML=calc(kind,v);window.dataLayer?.push({event:'calculator_completion',calculator:kind})});qs('.reset',box).addEventListener('click',()=>{for(const [k,val] of initial)form.elements[k].value=val;form.querySelectorAll('.field-error').forEach(x=>x.textContent='');qs('.result-content',box).innerHTML='<p>Enter your assumptions, then calculate.</p>'});form.requestSubmit()});globalThis.MarginFlipsTest={calculateROI,isValidInput};
